# 触发模式
TriggerMode=Both
# 命令键
CommandKeys=
# 后处理选单键
SceneMenuKey=

[TriggerKey]
0=Shift+Super+Assistant

[AsrMenuKey]
0=Alt+Super+Y

[PagePrevKeys]
0=Page_Up
1=KP_Page_Up

[PageNextKeys]
0=Next
1=KP_Next

